#!/usr/bin/env python3
"""Evaluate scene graph completeness and structured data accuracy.

Metrics required by the task:
  completeness = matched scene contents / actual scene contents
  structured accuracy = TP / (TP + FP + FN)

The script supports expert-review CSVs generated by build_scene_graph.py:
  expected_contents_template.csv
  expected_relations_template.csv
  node_review_template.csv
  edge_review_template.csv

Ground truth is not generated by this script. It must come from expert/acceptance
review of the real scene:
  - expected_contents: actual scene contents.
  - expected_relations: actual relations that should exist.
  - node_review/edge_review: correctness labels for predicted graph items.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from scene_graph_config import (  # noqa: E402
    SCENE_GRAPH_OUT_DIR,
    TARGET_COMPLETENESS,
    TARGET_STRUCTURED_ACCURACY,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate generated scene graph against expert review files.")
    parser.add_argument("--scene-graph", default=SCENE_GRAPH_OUT_DIR / "scene_graph.json", type=Path, help="scene_graph.json")
    parser.add_argument("--expected-contents", type=Path, default=SCENE_GRAPH_OUT_DIR / "expected_contents_template.csv", help="Actual scene content list CSV.")
    parser.add_argument("--expected-relations", type=Path, default=SCENE_GRAPH_OUT_DIR / "expected_relations_template.csv", help="Actual relation list CSV.")
    parser.add_argument("--node-review", type=Path, default=SCENE_GRAPH_OUT_DIR / "node_review_template.csv", help="Node correctness review CSV.")
    parser.add_argument("--edge-review", type=Path, default=SCENE_GRAPH_OUT_DIR / "edge_review_template.csv", help="Edge correctness review CSV.")
    parser.add_argument("--out", type=Path, default=SCENE_GRAPH_OUT_DIR / "scene_graph_metrics.json", help="Output metrics JSON.")
    parser.add_argument("--target-completeness", default=TARGET_COMPLETENESS, type=float)
    parser.add_argument("--target-structured-accuracy", default=TARGET_STRUCTURED_ACCURACY, type=float)
    parser.add_argument(
        "--allow-label-only-match",
        action="store_true",
        help="For expected contents/relations, allow automatic matching by labels when matched ids are empty.",
    )
    return parser.parse_args()


def read_csv(path: Path | None) -> list[dict]:
    if path is None or not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def parse_bool(value: object) -> int | None:
    raw = str(value).strip().lower()
    if raw in {"1", "true", "yes", "y", "对", "正确", "匹配"}:
        return 1
    if raw in {"0", "false", "no", "n", "错", "错误", "不匹配"}:
        return 0
    return None


def normalize_label(label: str) -> str:
    return " ".join(str(label).strip().lower().replace("_", " ").split())


def load_graph(path: Path) -> tuple[list[dict], list[dict]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload.get("nodes", []), payload.get("edges", [])


def auto_match_content(row: dict, nodes: list[dict]) -> str:
    expected = normalize_label(row.get("expected_label", ""))
    if not expected:
        return ""
    for node in nodes:
        if normalize_label(node.get("label", "")) == expected:
            return str(node.get("id", ""))
    return ""


def auto_match_relation(row: dict, nodes_by_id: dict[str, dict], edges: list[dict]) -> str:
    source_label = normalize_label(row.get("source_label", ""))
    relation = normalize_label(row.get("relation", ""))
    target_label = normalize_label(row.get("target_label", ""))
    if not source_label or not relation or not target_label:
        return ""
    for edge in edges:
        src = nodes_by_id.get(str(edge.get("source", "")), {})
        tgt = nodes_by_id.get(str(edge.get("target", "")), {})
        if (
            normalize_label(src.get("label", "")) == source_label
            and normalize_label(edge.get("relation", "")) == relation
            and normalize_label(tgt.get("label", "")) == target_label
        ):
            return str(edge.get("id", ""))
    return ""


def evaluate_completeness(expected_rows: list[dict], nodes: list[dict], allow_auto: bool) -> dict:
    total = 0
    matched = 0
    unresolved = 0
    matched_ids: list[str] = []
    for row in expected_rows:
        required = parse_bool(row.get("required", "1"))
        if required == 0:
            continue
        expected_label = str(row.get("expected_label", "")).strip()
        if not expected_label or expected_label.startswith("示例"):
            continue
        total += 1
        matched_node_id = str(row.get("matched_node_id", "")).strip()
        if not matched_node_id and allow_auto:
            matched_node_id = auto_match_content(row, nodes)
        value = 1 if matched_node_id else parse_bool(row.get("matched", ""))
        if value is None:
            unresolved += 1
            value = 0
        if value == 1:
            matched += 1
            if matched_node_id:
                matched_ids.append(matched_node_id)
    score = matched / total if total else None
    return {
        "matched_scene_content_count": matched,
        "actual_scene_content_count": total,
        "unresolved_items": unresolved,
        "completeness": score,
        "completeness_percent": score * 100 if score is not None else None,
        "matched_node_ids": matched_ids,
    }


def evaluate_review(rows: list[dict], id_field: str) -> tuple[int, int, set[str], int]:
    tp = 0
    fp = 0
    correct_ids: set[str] = set()
    unresolved = 0
    for row in rows:
        item_id = str(row.get(id_field, "")).strip()
        if not item_id or item_id.startswith("示例"):
            continue
        value = parse_bool(row.get("correct", ""))
        if value is None:
            unresolved += 1
            continue
        if value == 1:
            tp += 1
            correct_ids.add(item_id)
        else:
            fp += 1
    return tp, fp, correct_ids, unresolved


def evaluate_expected_relations(expected_rows: list[dict], nodes: list[dict], edges: list[dict], allow_auto: bool) -> dict:
    nodes_by_id = {str(node.get("id")): node for node in nodes}
    total = 0
    matched = 0
    unresolved = 0
    matched_edge_ids: set[str] = set()
    for row in expected_rows:
        required = parse_bool(row.get("required", "1"))
        if required == 0:
            continue
        if not str(row.get("relation", "")).strip() or str(row.get("relation_id", "")).startswith("示例"):
            continue
        total += 1
        matched_edge_id = str(row.get("matched_edge_id", "")).strip()
        if not matched_edge_id and allow_auto:
            matched_edge_id = auto_match_relation(row, nodes_by_id, edges)
        value = 1 if matched_edge_id else parse_bool(row.get("matched", ""))
        if value is None:
            unresolved += 1
            value = 0
        if value == 1:
            matched += 1
            if matched_edge_id:
                matched_edge_ids.add(matched_edge_id)
    return {
        "matched_relation_count": matched,
        "actual_relation_count": total,
        "unresolved_relations": unresolved,
        "matched_edge_ids": matched_edge_ids,
    }


def main() -> int:
    args = parse_args()
    nodes, edges = load_graph(args.scene_graph)
    expected_contents = read_csv(args.expected_contents)
    expected_relations = read_csv(args.expected_relations)
    node_review = read_csv(args.node_review)
    edge_review = read_csv(args.edge_review)

    completeness = evaluate_completeness(expected_contents, nodes, args.allow_label_only_match)

    node_tp, node_fp, correct_node_ids, node_unresolved = evaluate_review(node_review, "node_id")
    edge_tp, edge_fp, correct_edge_ids, edge_unresolved = evaluate_review(edge_review, "edge_id")
    relation_eval = evaluate_expected_relations(expected_relations, nodes, edges, args.allow_label_only_match)

    # FN comes from expected scene contents/relations not covered by generated/reviewed graph.
    content_fn = 0
    if completeness["actual_scene_content_count"]:
        content_fn = completeness["actual_scene_content_count"] - completeness["matched_scene_content_count"]
    relation_fn = 0
    if relation_eval["actual_relation_count"]:
        relation_fn = relation_eval["actual_relation_count"] - relation_eval["matched_relation_count"]

    # If no node/edge review is provided, count auto-matched expected contents/relations as TP
    # and leave FP at 0. This is useful for pre-checks; final acceptance should use review CSVs.
    if not node_review and completeness["matched_scene_content_count"]:
        node_tp = completeness["matched_scene_content_count"]
    if not edge_review and relation_eval["matched_relation_count"]:
        edge_tp = relation_eval["matched_relation_count"]

    tp = node_tp + edge_tp
    fp = node_fp + edge_fp
    fn = content_fn + relation_fn
    structured_accuracy = tp / (tp + fp + fn) if (tp + fp + fn) > 0 else None

    payload = {
        "scene_graph": str(args.scene_graph),
        "node_count": len(nodes),
        "edge_count": len(edges),
        "completeness_metric": {
            "definition": "matched_scene_content_count / actual_scene_content_count",
            **{k: v for k, v in completeness.items() if k != "matched_node_ids"},
            "target": args.target_completeness,
            "pass": completeness["completeness"] >= args.target_completeness if completeness["completeness"] is not None else None,
        },
        "structured_accuracy_metric": {
            "definition": "TP / (TP + FP + FN)",
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "node_tp": node_tp,
            "node_fp": node_fp,
            "edge_tp": edge_tp,
            "edge_fp": edge_fp,
            "content_fn": content_fn,
            "relation_fn": relation_fn,
            "node_unresolved": node_unresolved,
            "edge_unresolved": edge_unresolved,
            "expected_relation_count": relation_eval["actual_relation_count"],
            "matched_relation_count": relation_eval["matched_relation_count"],
            "structured_accuracy": structured_accuracy,
            "structured_accuracy_percent": structured_accuracy * 100 if structured_accuracy is not None else None,
            "target": args.target_structured_accuracy,
            "pass": structured_accuracy >= args.target_structured_accuracy if structured_accuracy is not None else None,
        },
        "gt_source": {
            "expected_contents": str(args.expected_contents) if args.expected_contents else None,
            "expected_relations": str(args.expected_relations) if args.expected_relations else None,
            "node_review": str(args.node_review) if args.node_review else None,
            "edge_review": str(args.edge_review) if args.edge_review else None,
            "description": "GT must be manually/expert-filled from the real scene or acceptance checklist. Example CSVs and label-only matching are only pre-checks.",
        },
    }

    out = args.out or (args.scene_graph.parent / "scene_graph_metrics.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print("[Scene Graph Metrics]")
    comp = payload["completeness_metric"]
    acc = payload["structured_accuracy_metric"]
    if comp["completeness"] is None:
        print("completeness              : pending expected_contents")
    else:
        print(f"completeness              : {comp['completeness_percent']:.2f}% ({comp['matched_scene_content_count']}/{comp['actual_scene_content_count']})")
        print(f"target >= {args.target_completeness * 100:.1f}%         : {'PASS' if comp['pass'] else 'FAIL'}")
    if acc["structured_accuracy"] is None:
        print("structured accuracy       : pending review/expected files")
    else:
        print(f"structured accuracy       : {acc['structured_accuracy_percent']:.2f}% (TP={tp}, FP={fp}, FN={fn})")
        print(f"target >= {args.target_structured_accuracy * 100:.1f}%         : {'PASS' if acc['pass'] else 'FAIL'}")
    print(f"[INFO] metrics JSON: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
